name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Новые возможности'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Исправления ошибок'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🔧 Технические изменения'
    labels:
      - 'chore'
      - 'documentation'
      - 'refactor'
  - title: '⚡️ Производительность'
    labels:
      - 'performance'
  - title: '🔒 Безопасность'
    labels:
      - 'security'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

template: |
  ## Что изменилось

  $CHANGES

  **Полный список изменений:** $DIFF_URL